import Head from "next/head";
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin,AiFillGithub, AiFillGoogleCircle, AiFillMail, AiFillPhone} from 'react-icons/ai';
import Image from "next/image";
import deved from '../public/dev-ed-wave.png';
import {useState} from "react";
import Web from '../public/web.jpg';
import Html from '../public/html.png';
import Css from '../public/css.png';
import Javascript from '../public/javascript.png';
import ReactImg from '../public/react.png';
import Tailwind from '../public/tailwind.png';
import Github from '../public/github1.png';
import Mongo from '../public/mongo.png';
import NextJS from '../public/nextjs.png';
import Node from '../public/node.png';
import Todo from '../public/todo.jpg';
import Calc from '../public/calculator.jpg';
import Web3 from '../public/web3blog.jpg';
import Zomato from '../public/zomato.jpg';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Guru Portfolio</title>
        <meta name="description" content="Generated by creator" />
        <link rel="icon" href="/favicon.ico" /> 
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">
              It's, Guru..
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">My Portfolio</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium ">Gurudeep K P</h2>
            <h3 className="text-2xl py-2 font-bold">Full Stack Developer(MERN)</h3>
            <p className="text-md py-5 leading-8 text-gray-800">I am a student with strong in design and integration with intuitive problem-solving skills.
              Proficient in Java, Python and Web Development.<br /> Passionate about implementing and launching new 
              projects. Ability to translate business requirements into technical solutions.<br /> Looking to start a 
              career as an entry level software engineer with a reputed firm driven by technology.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillLinkedin className="hover:scale-110"/>
            <AiFillGithub className="hover:scale-110"/>
            <AiFillGoogleCircle className="hover:scale-110" />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={deved} layout="fill" objectFit="cover"  />
          </div>
        <div id='about' className='w-full md:h-screen p-2 flex items-center py-16'>
          <div className='max-w-[1240px] m-auto md:grid grid-cols-3 gap-8'>
          <div className='col-span-2 mb-80'>
            <p className='uppercase text-5xl tracking-widest text-[#5651e5]'>
            About
            </p>
            <h2 className='py-4 text-3xl'>Who I Am</h2>
            <p className='py-2 text-gray-600'>
            I'm passionate about learning new technologies and understand there is
            more than one way to accomplish a task. Though I am most proficient
            in building front-end applications using HTML, CSS, Javascript, and
            React, and MERN Stack languages, I am a quick learner and can pick up new tech stacks as
            needed. I believe that being a great developer is not using one
            specific language, but choosing the best tool for the job.
            </p>
            <div className="w-38 h-38">
              <Image src={Web} alt='' className="rounded-xl" />
            </div>
          </div>
        </div>
      </div>

      <div id='skills' className='w-full lg:h-screen py-20 p-10 m-10'>
      <div className='max-w-[1240px] mx-auto flex-col justify-center h-full'>
        <p className='text-5xl tracking-widest uppercase text-[#5651e5]'>
          Skills
        </p>
        <h2 className='py-4 text-3xl'>What I Can Do</h2>
        <div className='grid grid-cols-2 lg:grid-cols-4 gap-8'>
          <div className='p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300'>
            <div className='grid grid-cols-2 gap-4 justify-center items-center'>
              <div className='m-auto'>
                <Image src={Html} width='64px' height='64px' alt='/' />
              </div>
              <div className='flex flex-col items-center justify-center'>
                <h3>HTML</h3>
              </div>
            </div>
          </div>
          <div className='p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300'>
            <div className='grid grid-cols-2 gap-4 justify-center items-center'>
              <div className='m-auto'>
                <Image src={Css} width='64px' height='64px' alt='/' />
              </div>
              <div className='flex flex-col items-center justify-center'>
                <h3>CSS</h3>
              </div>
            </div>
          </div>
          <div className='p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300'>
            <div className='grid grid-cols-2 gap-4 justify-center items-center'>
              <div className='m-auto'>
                <Image src={Javascript} width='64px' height='64px' alt='/' />
              </div>
              <div className='flex flex-col items-center justify-center'>
                <h3>JavaScript</h3>
              </div>
            </div>
          </div>
          <div className='p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300'>
            <div className='grid grid-cols-2 gap-4 justify-center items-center'>
              <div className='m-auto'>
                <Image src={ReactImg} width='64px' height='64px' alt='/' />
              </div>
              <div className='flex flex-col items-center justify-center'>
                <h3>React</h3>
              </div>
            </div>
          </div>
          <div className='p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300'>
            <div className='grid grid-cols-2 gap-4 justify-center items-center'>
              <div className='m-auto'>
                <Image src={Tailwind} width='64px' height='64px' alt='/' />
              </div>
              <div className='flex flex-col items-center justify-center'>
                <h3>Tailwind</h3>
              </div>
            </div>
          </div>
          <div className='p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300'>
            <div className='grid grid-cols-2 gap-4 justify-center items-center'>
              <div className='m-auto'>
                <Image src={Node} width='64px' height='64px' alt='/' />
              </div>
              <div className='flex flex-col items-center justify-center'>
                <h3>Node</h3>
              </div>
            </div>
          </div>
          <div className='p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300'>
            <div className='grid grid-cols-2 gap-4 justify-center items-center'>
              <div className='m-auto'>
                <Image src={Mongo} width='64px' height='64px' alt='/' />
              </div>
              <div className='flex flex-col items-center justify-center'>
                <h3>MongoDB</h3>
              </div>
            </div>
          </div>
          <div className='p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300'>
            <div className='grid grid-cols-2 gap-4 justify-center items-center'>
              <div className='m-auto'>
                <Image src={Github} width='64px' height='64px' alt='/' />
              </div>
              <div className='flex flex-col items-center justify-center'>
                <h3>Github</h3>
              </div>
            </div>
          </div>
          <div className='p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300'>
            <div className='grid grid-cols-2 gap-4 justify-center items-center'>
              <div className='m-auto'>
                <Image src={NextJS} width='64px' height='64px' alt='/' />
              </div>
              <div className='flex flex-col items-center justify-center'>
                <h3>Next</h3>
              </div>
            </div>
          </div>
        </div>
        </div>
        </div>

        <div>
          <h1 className="text-5xl text-gray-500 px-20 py-5">Projects</h1>
          <p className="text-2xl px-20 py-5 text-gray-800">
            Here are some of the basic projects I have practiced after learning the web development.<br/>
            It's so cool and had fun along with learning by doing it.
            </p>

            <div className='p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300'>
            <div className='grid grid-cols-2 gap-4 justify-center items-center'>
              <div className="m-auto">
                <Image src={Todo} width='64px' height='64px' alt='/' />
              </div>
              <h2 className="text-6xl px-20 text-orange-500">Task Tracker App</h2>
              <p className="text-2xl px-20 py-5">It is an task tracking frontend application that's build with React.<br/>
              It's a simple to-do list that helps us to remember the task to be done on time.<br/>The task is associated with day and time 
              and hence the checkbox to be noted<br/>for setting the remainder.<br /><br/>
              repo : github.com/Gurudeep25/react-task-tracker</p>
            </div>
          </div>

           <div className='p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300'>
            <div className='grid grid-cols-2 gap-4 justify-center items-center'>
              <div className="m-auto">
                <Image src={Calc} width='64px' height='64px' alt='/' />
              </div>
              <h2 className="text-6xl px-20 text-orange-500">Calculator App</h2>
              <p className="text-2xl px-20 py-5">It is a basic calculator frontend application that's build with React.<br/>
              The arithmetic operations such as addition, subtraction, multiplication and division are done here.<br />
              Every number is considered as a button with an onclick function to perform operations.<br /><br />
              repo : github.com/Gurudeep25/react-calc</p>
            </div>
          </div>

           <div className='p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300'>
            <div className='grid grid-cols-2 gap-4 justify-center items-center'>
              <div className="m-auto">
                <Image src={Web3} width='64px' height='64px' alt='/' />
              </div>
              <h2 className="text-6xl px-20 text-orange-500">Web3 - Blog</h2>
              <p className="text-2xl px-20 py-5">It is a web3 blog post application that runs on blockchain technology.<br/>
              The frontend part is usual react that helps the users to create an account with Metamask Wallet.<br />
              The backend part is full of smart contracts(Solidity) and here Ethers.js is used to communicate with frontend.<br /><br />
              repo : github.com/Gurudeep25/fullstack-web3</p>
            </div>
          </div>

          <div className='p-6 shadow-xl rounded-xl hover:scale-105 ease-in duration-300'>
            <div className='grid grid-cols-2 gap-4 justify-center items-center'>
              <div className="m-auto">
                <Image src={Zomato} width='64px' height='64px' alt='/' />
              </div>
              <h2 className="text-6xl px-20 text-orange-500">Zomato Clone (MERN)</h2>
              <p className="text-2xl px-20 py-5">The MERN Stack application that is as functional as Zomato.<br/>
              With added benefits using modern technology and latest user experience standards such as user<br />
              registration, restaurant search, filteration, menu viewing, payment processing, deployment,etc.<br /><br />
              repo : github.com/Gurudeep25/zomato-clone</p>
            </div>
          </div>

          </div>
      </section>
      <footer>
        <h1 className="text-5xl px-20 py-5 text-red-800">Let's Get in Touch!</h1>
        <h3 className="text-3xl px-20 text-yellow-500">Reach me out at,</h3>
        <p className="text-2xl px-20 py-5 text-blue-500">
          <AiFillMail className="hover:scale-110 text-5xl" /> gurukp02@gmail.com <br /> 
          <AiFillPhone className="hover:scale-110 text-5xl" /> +91 7200930408 <br />  
          <AiFillGithub className="hover:scale-110 text-5xl" /> github.com/Gurudeep25 <br /> 
          <AiFillLinkedin className="hover:scale-110 text-5xl" /> https://www.linkedin.com/in/gurudeep-k-p-88327618a
        </p>
        <div className="py-4 text-center bg-primary text-gray-500 "> &copy; 2023 Gurudeep all rights reserved</div>
      </footer>
  </main>
</div>
  );
}